// <auto-generated />
using System;
using CajemesfoodProyect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CajemesfoodProyect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.Administrador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LocalId")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("LocalId");

                    b.ToTable("administradors");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.Local", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("local");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.Local_proveedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("localId")
                        .HasColumnType("int");

                    b.Property<int>("proveedorId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("localId");

                    b.HasIndex("proveedorId");

                    b.ToTable("localProveedors");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.platillos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("caducidad")
                        .HasColumnType("datetime2");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("platillos");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.platillos_Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LocalId")
                        .HasColumnType("int");

                    b.Property<int>("platilloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalId");

                    b.HasIndex("platilloId");

                    b.ToTable("platillos_Locals");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.proveedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("proveedors");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.Administrador", b =>
                {
                    b.HasOne("CajemesfoodProyect.Data.Models.Local", "Local")
                        .WithMany("administradors")
                        .HasForeignKey("LocalId");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.Local_proveedor", b =>
                {
                    b.HasOne("CajemesfoodProyect.Data.Models.Local", "localid")
                        .WithMany("localProveedors")
                        .HasForeignKey("localId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CajemesfoodProyect.Data.Models.proveedor", "proveedor")
                        .WithMany("localProveedors")
                        .HasForeignKey("proveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("localid");

                    b.Navigation("proveedor");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.platillos_Local", b =>
                {
                    b.HasOne("CajemesfoodProyect.Data.Models.Local", "Local")
                        .WithMany("platillos_Locals")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CajemesfoodProyect.Data.Models.platillos", "platillos")
                        .WithMany("platillos_Locals")
                        .HasForeignKey("platilloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");

                    b.Navigation("platillos");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.Local", b =>
                {
                    b.Navigation("administradors");

                    b.Navigation("localProveedors");

                    b.Navigation("platillos_Locals");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.platillos", b =>
                {
                    b.Navigation("platillos_Locals");
                });

            modelBuilder.Entity("CajemesfoodProyect.Data.Models.proveedor", b =>
                {
                    b.Navigation("localProveedors");
                });
#pragma warning restore 612, 618
        }
    }
}
